### ISSUE TITLE
[BUG]: ansible-builder introspect fails with file not found

### ISSUE THREAD

**Issue by carlosgo13** [dell/ansible-powerstore#14]
Hello team.

When attempting to install this collection into an execution environment via the ansible-builder command, the build fails with an error that the requirements.txt file is not found. This seems to be caused by the use of a relative path in the meta/execution-environment.yml file. Instead of using relative paths you may use absolute paths.

Best regards.

**Comment by carlosgo13** [comment]
Similar issue here: https://github.com/dell/ansible-powerscale/issues/32

**Comment by anupamaloke** [comment]
Closing this issue as it has been fixed with #17
