### ISSUE TITLE
[BUG]: smtp_config doesn't work unless smtp is already configured

### ISSUE THREAD

**Issue by jason-technology** [dell/ansible-powerstore#28]
**Describe the bug**
.smtp_config works fine for state management
Is does not perform initial SMTP Server configuration
smtp_id 0 does not exist until SMTP is configured for the first time

**To Reproduce**
1. Step 1 Run smtp_config against brand new cluster
2. Step 2 Observe Failure message ~"SMTP Server ID 0 does not exist"
3. Step 3 Manually enable SMTP
4. Step 4 Run smtp_config against cluster
5. Step 5 Observer success
...

**Expected behavior**
I would expect this module to be able to perform initial configuration of a new cluster

**System Information (please complete the following information):**
 PowerStore 3.2
Ansible PowerStore 1.9(latest)

Issue was present on earlier versions but did not report at that time

**Comment by Jennifer-John** [comment]
Fix merged as part of PR #31
