### ISSUE TITLE
[BUG]: Creating NFS exports wrongfully checks for existing exports

### ISSUE THREAD

**Issue by tsarajar** [dell/ansible-powerstore#36]
**Describe the bug**
When creating an NFS export, these scripts prevent you from creating an export with the same (nfs_export_name) as an already existing export, even if those exports are on a different NAS and filesystem. The GUI of Powerstore allows you to do that.

**To Reproduce**
1. Create 2 NAS servers
2. Create filesystems on both of them
3. Create exports with the same name from those 2 different NAS servers and filesystems
4. This fails when done via Ansible, but works when doing manually via GUI

**Expected behavior**
Well I should be able to do the exports with the same name

**Logs**
failed: [server -> ansible-controller] (item=ps01-nfs02) => {"ansible_loop_var": "item", "changed": false, "item": "ps01-nfs02", "msg": "Entered filesystem/snapshot/nas_server/path do not match with the corresponding NFS Export details. Please provide valid parameters."}

**Comment by anupamaloke** [comment]
Closed via #39
