### ISSUE TITLE
[QUESTION]: Not able to clone the repo

### ISSUE THREAD

**Issue by vipal31** [dell/ansible-powerstore#9]
### How can the Team help you today?

**Details: ?** When I try to clone the repo on linux machine, I am getting below message

controller:~$ git clone https://github.com/dell/python-powerstore/tree/1.5.0
Cloning into '1.5.0'...
**fatal: repository 'https://github.com/dell/python-powerstore/tree/1.5.0/' not found****
controller:~$

**Comment by anupamaloke** [comment]
Closing this issue as no updates for a long time.
